version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3102:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
